# Generated by Django 4.0.1 on 2022-01-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, null=True),
        ),
    ]
