# Generated by Django 4.0.1 on 2022-01-25 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='questions',
        ),
        migrations.RenameModel(
            old_name='Answer',
            new_name='SubQuestionAnswer',
        ),
        migrations.CreateModel(
            name='ResultQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_answer', models.CharField(max_length=2)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.responder')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subquestion')),
                ('sub_question_answers', models.ManyToManyField(to='core.SubQuestionAnswer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
