# Generated by Django 4.0.1 on 2022-01-26 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subquestion_creator_subquestionanswer_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sub_question',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.questionnaire'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.question'),
        ),
    ]
