# Generated by Django 4.0.1 on 2022-01-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_subquestion_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
