# Generated by Django 4.0.1 on 2022-01-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_questionnaire_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='counter',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='interrogator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='core.interrogator'),
        ),
    ]
